### ISSUE TITLE
Erro de ortografia para o número 17

### ISSUE THREAD

**Issue by Helidalto** [wgenial/numeroporextenso-php#4]
Olá, 
Existe um erro de ortografia na palavra "dezesete", o correto é dezessete.

**Comment by giovanigenerali** [comment]
@Helidalto vou corrigir, obrigado.

**Comment by giovanigenerali** [comment]
Corrigido https://github.com/wgenial/numeroporextenso-php/commit/699632039e8978cd4e688f5aeb0a97e0274fecf6
